### ISSUE TITLE
Couldn't load plugin 'deepness' due to an error when calling its classFactory() method: ModuleNotFoundError: No module named 'cv2' 

### ISSUE THREAD

**Issue by kristianrl** [PUTvision/qgis-plugin-deepness#119]
I have a fresh installation of QGIS 3.22.2, and installed the Deepness-plugin. It resulted in the following error message:

```
Couldn't load plugin 'deepness' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'cv2' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/MY_USERNAME/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deepness\__init__.py", line 18, in classFactory
    from deepness.deepness import Deepness
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/MY_USERNAME/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deepness\deepness.py", line 25, in 
    from deepness.deepness_dockwidget import DeepnessDockWidget
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/MY_USERNAME/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deepness\deepness_dockwidget.py", line 25, in 
    from deepness.processing.models.detector import Detector
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/MY_USERNAME/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deepness\processing\models\detector.py", line 6, in 
    import cv2
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'cv2'


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.32.2-Lima Lima, c0b8833964 

Python Path:
C:/PROGRA~1/QGIS33~1.2/apps/qgis/./python
C:/Users/MY_USERNAME/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/MY_USERNAME/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.2/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS33~1.2\apps\grass\grass83\etc\python
C:\Users\Default\Documents
C:\Program Files\QGIS 3.32.2\bin\python39.zip
C:\PROGRA~1\QGIS33~1.2\apps\Python39\DLLs
C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib
C:\Program Files\QGIS 3.32.2\bin
C:\PROGRA~1\QGIS33~1.2\apps\Python39
C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\site-packages\Pythonwin
C:/Users/MY_USERNAME/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\MY_USERNAME\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mapflow\dialogs\widgets
C:\Users\MY_USERNAME\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\deepness\python3.9
```

Can you make sure the cv2 module is installed if not met during installation?

Looking forward to trying your plugin, Kristian

**Comment by kristianrl** [comment]
This was solved by re-installation - the dependency window popped up below the QGIS main and plugin window.
