### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by robmarkcole** [PUTvision/qgis-plugin-deepness#183]
**Describe the bug**
Running the Storage tank model on Bing, as per the example video
```
Traceback (most recent call last):
  File "/Users/robin.cole/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/deepness/deepness.py", line 268, in _run_model_inference
    self._map_processor = map_processor_class(
  File "/Users/robin.cole/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/deepness/processing/map_processor/map_processor_detection.py", line 27, in __init__
    super().__init__(
  File "/Users/robin.cole/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/deepness/processing/map_processor/map_processor_with_model.py", line 18, in __init__
    super().__init__(
  File "/Users/robin.cole/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/deepness/processing/map_processor/map_processor.py", line 70, in __init__
    self.base_extent = extent_utils.calculate_base_processing_extent_in_rlayer_crs(
  File "/Users/robin.cole/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/deepness/processing/extent_utils.py", line 172, in calculate_base_processing_extent_in_rlayer_crs
    expected_extent = round_extent_to_rlayer_grid(extent=expected_extent, rlayer=rlayer)
  File "/Users/robin.cole/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/deepness/processing/extent_utils.py", line 29, in round_extent_to_rlayer_grid
    x_min = grid_start[0] + int((extent.xMinimum() - grid_start[0]) / grid_spacing[0]) * grid_spacing[0]
ValueError: cannot convert float NaN to integer
```

**Screenshots (including Deepness options selected)**
<img width="1915" alt="image" src="https://github.com/user-attachments/assets/269fee29-c0bf-4d42-8cfb-0950090867f4">

**Desktop (please complete the following information):**
 - OS: Mac
 - QGiS version: 3.38.2-Grenoble
 - Deepness version: latest

**Comment by robmarkcole** [comment]
When I change to `Visible part` and changed the resolution, the error is cleared

<img width="1919" alt="image" src="https://github.com/user-attachments/assets/8e08e21e-e99e-4ed1-896a-dcfc71ae70e9">

**Comment by przemyslaw-aszkowski** [comment]
Hi,
thanks for reporting. I suspect the issue was caused by the resolution per pixel being too high (20000 cm/pixel), and probably some dimension was divided by zero. Nevertheless, it is worth adding a sanity check to the code to create a meaningful error message :)
Cheers
Przemek
