### ISSUE TITLE
problems of installing the deepness plugin stettings

### ISSUE THREAD

**Issue by vott-coder** [PUTvision/qgis-plugin-deepness#197]
Hi, I wanted to install the deepness plugin to use it for determining the trees on our rasterfile.
I've followed these instructions on the paper:
https://mapscaping.com/deep-learning-image-segmentation-qgis/  
and in step 6 I've got these errors:

Installation of required packages finished. Validating installation...
Python packages required by the plugin could not be loaded due to the following error: 
Traceback (most recent call last):
  File "C:\Users/veerle.ott/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deepness\dialogs\packages_installer\packages_installer_dialog.py", line 300, in _check_packages_installation_and_log
    import_packages()
  File "C:\Users/veerle.ott/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deepness\dialogs\packages_installer\packages_installer_dialog.py", line 325, in import_packages
    import_package(package)
  File "C:\Users/veerle.ott/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deepness\dialogs\packages_installer\packages_installer_dialog.py", line 320, in import_package
    importlib.import_module(package.import_name)
  File "C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "", line 1030, in _gcd_import
  File "", line 1007, in _find_and_load
  File "", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cv2'

What can I do?
thanks in advance

**Comment by bartoszptak** [comment]
Hi @vott-coder!
First, check [this](https://github.com/PUTvision/qgis-plugin-deepness/issues/119#issuecomment-1793663744) issue.

If you are a more advanced user, check these steps:

### Update the OpenCV (cv2) library in QGIS:

1. Open the Python console in QGIS (Ctrl + Alt + P)
2. Import the PIP library by typing `import pip`
3. Then, update (or install) OpenCV by typing `pip.main(['install', '--upgrade', 'opencv-python'])`
4. You should see the last message, such as `Successfully installed opencv-python`
5. Restart QGIS

If the error still exists, you need to respond to the questions:
**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 22.04]
 - QGiS version
 - Deepness version 

In the future, we plan to record tutorials for Ubuntu and Windows systems on how to install Deepness, including the most often issues solved. Furthermore, we plan to manage some specific cases in the plugin background, but it is challenging to maintain compatibility for all OSes and QGIS, python, and library versions.

**Comment by vott-coder** [comment]
> Hi @vott-coder! First, check [this](https://github.com/PUTvision/qgis-plugin-deepness/issues/119#issuecomment-1793663744) issue.
> 
> If you are a more advanced user, check these steps:
> 
> ### Update the OpenCV (cv2) library in QGIS:
> 1. Open the Python console in QGIS (Ctrl + Alt + P)
> 2. Import the PIP library by typing `import pip`
> 3. Then, update (or install) OpenCV by typing `pip.main(['install', '--upgrade', 'opencv-python'])`
> 4. You should see the last message, such as `Successfully installed opencv-python`
> 5. Restart QGIS
> 
> If the error still exists, you need to respond to the questions: **Desktop (please complete the following information):**
> 
> * OS: [e.g. Windows 10, Ubuntu 22.04]
> * QGiS version
> * Deepness version
> 
> In the future, we plan to record tutorials for Ubuntu and Windows systems on how to install Deepness, including the most often issues solved. Furthermore, we plan to manage some specific cases in the plugin background, but it is challenging to maintain compatibility for all OSes and QGIS, python, and library versions.

**Comment by vott-coder** [comment]
Hi, after re-installing still the same error but in the logbook for plug-ins:

2024-12-13T13:13:52     INFO    Geladen GRASS 8 (Pad: C:/PROGRA~1/QGIS33~1.13/apps/qgis-ltr/plugins/plugin_grass8.dll)
2024-12-13T13:13:58     INFO    Geladen Deepness: Deep Neural Remote Sensing (package: deepness)
2024-12-13T13:13:59     INFO    Geladen Freehand raster georeferencer (package: FreehandRasterGeoreferencer)
2024-12-13T13:14:05     INFO    Geladen geopunt4Qgis (package: geopunt4Qgis)
2024-12-13T13:14:08     INFO    Geladen QuickMapServices (package: quick_map_services)
2024-12-13T13:14:08     INFO    Geladen RasterStats (package: rasterstats)
2024-12-13T13:14:08     INFO    Geladen DB Manager (package: db_manager)
2024-12-13T13:14:10     INFO    Geladen MetaSearch Catalog Client (package: MetaSearch)
2024-12-13T13:14:14     INFO    Geladen Processing (package: processing)
2024-12-13T13:17:08     INFO    Geladen Deepness: Deep Neural Remote Sensing (package: deepness)

Installation of required packages finished. Validating installation...
Python packages required by the plugin could not be loaded due to the following error: 
Traceback (most recent call last):
  File "C:\Users/veerle.ott/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deepness\dialogs\packages_installer\packages_installer_dialog.py", line 300, in _check_packages_installation_and_log
    import_packages()
  File "C:\Users/veerle.ott/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deepness\dialogs\packages_installer\packages_installer_dialog.py", line 325, in import_packages
    import_package(package)
  File "C:\Users/veerle.ott/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deepness\dialogs\packages_installer\packages_installer_dialog.py", line 320, in import_package
    importlib.import_module(package.import_name)
  File "C:\PROGRA~1\QGIS33~1.13\apps\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "", line 1387, in _gcd_import
  File "", line 1360, in _find_and_load
  File "", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cv2'

I've also tried this but didn't see the message (successfully installed...), but I am not an experienced user...
Update the OpenCV (cv2) library in QGIS:
Open the Python console in QGIS (Ctrl + Alt + P)
Import the PIP library by typing import pip
Then, update (or install) OpenCV by typing pip.main(['install', '--upgrade', 'opencv-python'])
You should see the last message, such as Successfully installed opencv-python
Restart QGIS

Windows 11 enterprise
QGIS 3.34.13
Deepness 0.6.5.

**Comment by przemyslaw-aszkowski** [comment]
Hi, it seems Deepness cannot install the opencv python package (ModuleNotFoundError: No module named 'cv2'). Please try to install it manually, I think there were already some detailed instructions in the issues.
Let me know if you cannot find it.

**Comment by vott-coder** [comment]
Hi, now I've got this:


import pip
pip.main(['install', 'opencv-python'])
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)'))': /simple/opencv-python/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)'))': /simple/opencv-python/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)'))': /simple/opencv-python/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)'))': /simple/opencv-python/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)'))': /simple/opencv-python/
Could not fetch URL https://pypi.org/simple/opencv-python/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/opencv-python/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)'))) - skipping
ERROR: Could not find a version that satisfies the requirement opencv-python (from versions: none)
ERROR: No matching distribution found for opencv-python
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)'))) - skipping
1
import -m pip
  File "<input>", line 1
    import -m pip
           ^
SyntaxError: invalid syntax




Met vriendelijke groeten



Veerle Ott

Deskundige Gis & Data-analyse

stad Sint-Niklaas

Stadhuis

Grote Markt 1– 9100 Sint-Niklaas

Tel 03/7783532

GSM 0499/980890


www.sint-niklaas.be<http://www.sint-niklaas.be/>


[cid:27393d1d-bef8-4634-ace1-b8f3d1e09893]

________________________________
Van: przemyslaw-aszkowski ***@***.***>
Verzonden: vrijdag 13 december 2024 13:28
Aan: PUTvision/qgis-plugin-deepness ***@***.***>
CC: Veerle Ott ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [PUTvision/qgis-plugin-deepness] problems of installing the deepness plugin stettings (Issue #197)


Hi, it seems Deepness cannot install the opencv python package (ModuleNotFoundError: No module named 'cv2'). Please try to install it manually, I think there were already some detailed instructions in the issues.
Let me know if you cannot find it.

**Comment by AlainFELER** [comment]
Hello, Did you try what I describe in the #193 issue : https://github.com/PUTvision/qgis-plugin-deepness/issues/193 ?
NB : I did that from the command-line, not from the Python interpreter.
Maybe you could also update QGIS : it will update also all the Python environment.
Yours, AF

**Comment by JuliocGis** [comment]
Cordial saludo, estuve haciendo un ensayo para realizar, la función del complemento, (Deepness: Deep Neural Remote Sensing) pero a la hora de ejecutarlo, me aparece un error, adjunto la imagen de referencia.

![Image](https://github.com/user-attachments/assets/f364b414-5a0a-47ac-8e2f-458404fb20fb)


Me sale este error 
Error! Processing error: "Unhandled exception occurred. See Python Console for details"!


Details: IndexError - index 1 is out of bounds for axis 0 with size 1
Last Traceback: 
  File "C:\Users/ADMIN/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deepness\processing\models\detector.py", line 214, in postprocessing
    boxes, conf, classes = self._postprocessing_YOLO_v5_v7_DEFAULT(model_output[0][i])
                                                                   ~~~~~~~~~~~~~~~^^^


De ante mano le agradezco su pronta respuesta muchas gracias

**Comment by nmalcolm** [comment]
> Cordial saludo, estuve haciendo un ensayo para realizar, la función del complemento, (Deepness: Deep Neural Remote Sensing) pero a la hora de ejecutarlo, me aparece un error, adjunto la imagen de referencia.
> 
> ![Image](https://github.com/user-attachments/assets/f364b414-5a0a-47ac-8e2f-458404fb20fb)
> 
> Me sale este error Error! Processing error: "Unhandled exception occurred. See Python Console for details"!
> 
> Details: IndexError - index 1 is out of bounds for axis 0 with size 1 Last Traceback: File "C:\Users/ADMIN/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deepness\processing\models\detector.py", line 214, in postprocessing boxes, conf, classes = self._postprocessing_YOLO_v5_v7_DEFAULT(model_output[0][i]) ~~~~~~~~~~~~~~~^^^
> 
> De ante mano le agradezco su pronta respuesta muchas gracias

I'm also getting this error.
